<?xml version="1.0" ?>
<robot name="sia20d_workspace" xmlns:xacro="http://ros.org/wiki/xacro">
	<include filename="$(find motoman_config)/cfg/sia20d_mesh_macro.xacro"/>
	<include filename="$(find robot_config)/urdf/vacuum_gripper_macro.xacro"/>
	<include filename="$(find robot_config)/urdf/workspace_components.xacro"/>
	<include filename="$(find robot_config)/urdf/kinect_sensor_macro.xacro"/>

	<!-- property list -->
	<xacro:property name="workcell_height" value="1"/>
	<xacro:property name="coupler_height" value="0.087"/>
        <xacro:property name="attached_object_length" value="0.17"/>
	<xacro:property name="attached_object_width" value="0.17"/>
	<xacro:property name="attached_object_height" value="0.17"/>
	<xacro:property name="arm_prefix" value=""/>
	

	<!-- instantiating workcell definitions -->
	<xacro:workcell_zone1_components/>
	<!-- end of workcell definitions -->

	<link name="roof1">
		<collision>
			<geometry>
				<box size="0.921 2.220 0.04"/>
			</geometry>
		</collision>	
	</link>

	<link name="attached_object_link">
		<collision>
			<geometry>
				<box size="${attached_object_length} ${attached_object_width} ${attached_object_height}"/>
			</geometry>
			<material name="blue_transparent"/>
		</collision>
	</link>


	<!-- instantiating sensor definitions -->
	<xacro:sensor_definitions prefix="${arm_prefix}" parent_link="${arm_prefix}base_link" 
		x_val="1.010" y_val="0.169" z_val="1.206" roll="0.005" pitch="1.968" yaw="0.0"/>
	<!-- end of sensor definitions -->

	<!-- instantiating arm and gripper -->	
	<xacro:vacuum_gripper_definition prefix="${arm_prefix}" gripper_adjustment="-0.01"/>
	<xacro:sia20d_mesh prefix="${arm_prefix}"/>

	<!-- arm-workcell joint definitions -->
	<joint name="world_to_base" type="fixed">
		<parent link="world_frame"/>
		<child link="${arm_prefix}base_link"/>
		<origin xyz="0.241 0 0" rpy="0 0 0"/>
	</joint>

	<joint name="world_to_roof1" type="fixed">
		<parent link="world_frame"/>
		<child link="roof1"/>
		<origin xyz="0.987 0 1.20" rpy="0 0 0"/>
	</joint>
		
	<joint name="tcp_to_attached_object" type="fixed">
		<parent link="tcp_frame"/>
		<child link="attached_object_link"/>
		<origin xyz="0 0 ${0.5 * attached_object_height}"/>
	</joint>

	<!-- end of arm workcell joint definitions-->

	<!-- start of arm-gripper coupling link definitions-->
	<link name="${arm_prefix}coupler">
		<visual>
			<geometry>
				<mesh filename="package://robot_config/meshes/coupler/visual/COUPLER.stl" />
			</geometry>
			<material name="orange">
				<color rgba="1 0.5 0 1"/>
			</material>
		</visual>
		<collision>
			<geometry>
				<mesh filename="package://robot_config/meshes/coupler/collision/COUPLER.stl" />
			</geometry>
			<material name="yellow">
				<color rgba="0 1 1 1"/>
			</material>
		</collision>
	</link>
	<!-- end of arm-gripper coupling link definitions -->	

	<!-- start of arm-gripper coupling joint definitions -->
	<joint name="${arm_prefix}wrist_to_coupler" type="fixed">
		<parent link="${arm_prefix}link_t"/>
		<child link="${arm_prefix}coupler"/>
		<origin xyz="0 0 0" rpy="1.570 0 -0.785"/>
	</joint>

	<joint name="${arm_prefix}coupler_to_gripper" type="fixed">
		<parent link="${arm_prefix}coupler"/>
		<child link="${arm_prefix}gripper_frame"/>
		<origin xyz="0 ${coupler_height} 0" rpy="-1.570 3.14 0"/>
	</joint>
	<!-- end of arm-gripper coupling joint definitions -->

</robot>
