<?xml version="1.0" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
	<!-- parameter list -->
	<xacro:property name="cylinder_length" value="0.07"/>
	<xacro:property name="cylinder_radius" value="0.075"/>
	<xacro:property name="sphere_radius" value="0.075"/>
	<xacro:property name="gripper_length" value=".22"/>

	    <xacro:macro name="versaball_definition" params="prefix gripper_adjustment">
	      <link name="${prefix}gripper_frame"/>
	      <link name="${prefix}gripper_body">
	      <visual><!-- TODO EXCHANGE OR STL FROM MFG -->
		<origin xyz="0 0 0" rpy="0 0 0"/>
		  <geometry>
		    <cylinder length="${cylinder_length}" radius="${cylinder_radius}"/>
		  </geometry>
		  <material name="myblue">
		    <color rgba="0.0 0.0 0.8 1"/>
		  </material>
	      </visual>

	      <collision><!-- air hose  -->
		<origin xyz="-0.1 0 0" rpy="0 0 0"/>
		  <geometry>
		    <box size="0.1 0.08 0.02"/>
		  </geometry>
	      </collision>
	      <collision><!-- air hose  -->
		<origin xyz="-0.15 0 -.05" rpy="0 0 0"/>
		  <geometry>
		    <box size="0.02 0.08 0.1"/>
		  </geometry>
	      </collision>

	      
	      <collision>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		  <geometry>
		    <cylinder length="${cylinder_length}" radius="${cylinder_radius}"/>
		  </geometry>
		  <material name="myblue">
		    <color rgba="0.0 0.0 0.8 1"/>
		  </material>
	      </collision>

	    </link>
	      <link name="${prefix}gripper_body2">
	      <visual>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		  <material name="mygreen">
		    <color rgba="0.5 1.0 0.0 1"/>
		  </material>
		  <geometry>
		    <sphere radius="${sphere_radius}"/>
		  </geometry>
	      </visual>
	      <collision>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		  <material name="mygreen">
		    <color rgba="0.5 1.0 0.0 1"/>
		  </material>
		  <geometry>
		    <cylinder length="${sphere_radius * 1.6}" radius="${sphere_radius}"/>
		  </geometry>
	      </collision>
	    </link>
		<link name="${prefix}tcp_frame"/>
		<joint name="${prefix}gripper_to_palm" type="fixed">
			<parent link="${prefix}gripper_frame"/>
			<child link="${prefix}gripper_body"/>
			<origin xyz="0 0 ${cylinder_length/2.0}" rpy="0 0 0"/>
		</joint>
		<joint name="${prefix}gripper_to_palm2" type="fixed">
			<parent link="${prefix}gripper_frame"/>
			<child link="${prefix}gripper_body2"/>
			<origin xyz="0 0 ${cylinder_length + sphere_radius}" rpy="0 0 0"/>
		</joint>
		<joint name="${prefix}gripper_to_tcp" type="fixed">
			<parent link="${prefix}gripper_frame"/>
			<child link="${prefix}tcp_frame"/>
			<origin xyz=" 0 0 ${cylinder_length + sphere_radius * 1.6}" rpy="0 0 0"/>
		</joint>	
	</xacro:macro>
</robot>
